FROM python:3.12-slim

WORKDIR /app

# system
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1


# uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# dependencies
COPY pyproject.toml ./
RUN uv pip install --system .

# code base
COPY src/agents ./src/agents

# default
ENV FASTAPI_WORKERS=4
ENV PORT=80

EXPOSE 80

# run
CMD ["sh", "-c", "uvicorn src.agents.main:app --host 0.0.0.0 --port ${PORT} --workers ${FASTAPI_WORKERS:-4}"]