FROM python:3.12-slim

WORKDIR /app

# system
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# dependencies
COPY pyproject.toml ./
RUN uv pip install --system .

# code base
COPY src/idu_mcp ./src/idu_mcp

# default
ENV FASTMCP_WORKERS=1
ENV PORT=8000

EXPOSE 8000

# run
CMD ["sh", "-c", "uvicorn src.idu_mcp.main:mcp_app --host 0.0.0.0 --port ${PORT} --workers ${FASTMCP_WORKERS:-1}"]