services:
  idu_agents:
    image: ${AGENTS_IMAGE}
    container_name: ${AGENTS_CONTAINER_NAME}
    restart: always
    ports:
      - "80:80"
    env_file:
      - ./env/.env.agents.production

  idu_mcp:
    image: ${MCP_IMAGE}
    container_name: ${MCP_CONTAINER_NAME}
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./env/.env.idu_mcp.production
