version: "3.9"

services:

  idu_agents:
    build:
      context: .
      dockerfile: docker/Dockerfile-agents
    container_name: agents
    ports:
      - "80:80"
    env_file:
      - ./env/.env.agents.example
    networks:
      - localnet

  idu_mcp:
    build:
      context: .
      dockerfile: docker/Dockerfile-mcp
    container_name: idumcp
    ports:
      - "8000:8000"
    env_file:
      - ./env/.env.idu_mcp.example
    networks:
      - localnet

networks:
  localnet:
    external: true
