"""
Module aimed to handle requests to ChatStorage service REST API.
"""

from typing import Any

from src.agents.api_clients.chat_storage_client.entities import (
    MessageUploadType,
    RoleEnum,
)
from src.agents.api_clients.chat_storage_client.responses import (
    ChatCreated,
    MessageAdded,
)
from src.agents.common.api_handlers.json_api_handler import JsonApiHandler


# TODO add https statuses handling
class ChatStorageApiClient:

    def __init__(self, json_handler: JsonApiHandler) -> None:
        self.json_handler = json_handler
        self.__name__ = "ChatStorageApiClient"

    async def create_chat(
        self, token: str, title: str, scenario_id: int | None = None, **kwargs: Any
    ) -> ChatCreated:
        """
        Function creates chat with provided parameters.
        Args:
            token (str): Auth token from Urban API.
            title (str): Generated by llm chat title.
            scenario_id (int | None): Scenario ID from Urban API. Default to None.
            **kwargs (Any): Additional parameters for chat creation passed to meta.
        Returns:
            dict[str, str]: Dict with "chat_id" and "title" data from created chat.
        """

        data_to_post = {"title": title, "scenario_id": scenario_id, "meta": kwargs}
        chat = await self.json_handler.post(
            endpoint="/api/v1/chat_history/create_chats",
            auth_token=token,
            data={k: v for k, v in data_to_post.items() if v},
        )
        return ChatCreated(chat_id=chat["chat_id"], title=chat["title"])

    async def add_single_message(
        self,
        token: str,
        chat_id: str,
        role: RoleEnum | str,
        content: str,
        **kwargs: Any,
    ) -> MessageAdded:
        """
        Function adds single message to chat storage.
        Args:
            token (str): Authorization token from Urban API.
            chat_id (str): String representation of chat uuid.
            role (RoleEnum | str): Message role as RoleEnum. Available values: "user", "system", "assistant".
            content (str): Message to post as string.
            **kwargs (Any): Additional parameters for chat creation passed to meta.
        """

        message = await self.json_handler.post(
            endpoint=f"/api/v1/chat_history/{chat_id}/message",
            auth_token=token,
            data={
                "role": RoleEnum.parse(role).value,
                "content": content,
                "meta": kwargs,
            },
        )
        return MessageAdded(
            chat_id=message["message_id"],
            message_id=message["chat_id"],
            message_type=MessageUploadType.TEXT,
        )

    async def add_parts_message(
        self, token: str, chat_id: str, role: RoleEnum | str, parts: list, **kwargs
    ):

        pass
