from __future__ import annotations

import re
from typing import Any

# Record boundaries are generated by the application, not inferred from [N]
# references in the document's bibliography. Escape this character in source text.
SOURCE_SEPARATOR = "\x1e"


def source_records(context: str) -> dict[str, tuple[str, str]]:
    blocks = (
        context.split(SOURCE_SEPARATOR)
        if SOURCE_SEPARATOR in context
        else re.split(r"(?=^\[\d+\] )", context, flags=re.M)
    )
    records = {}
    for block in filter(None, (b.strip() for b in blocks)):
        header, _, body = block.partition("\n")
        label = re.match(r"^(\[\d+\])(?:\s|$)", header)
        source_id = label[1] if label else "unlabelled"
        if not label:
            header, body = "", block
        if source_id in records:
            body = records[source_id][1] + "\n" + body
        records[source_id] = (header, body)
    return records


class DvdContextBuilder:
    """
    Formats IDU_DVD search hits into a numbered, citable context string for the LLM.

    Each hit becomes a block headed by ``[N] <document>, ред. <version>, п. <numbering> — <breadcrumb>``
    so the answering model can ground its response and cite sources by number and clause.
    """

    def build_context(self, hits: list[dict[str, Any]]) -> str:
        if not hits:
            return ""
        return "".join(
            self._format_hit(index, hit).replace(SOURCE_SEPARATOR, "\\u001e")
            + SOURCE_SEPARATOR
            for index, hit in enumerate(hits, start=1)
        )

    def _format_hit(self, index: int, hit: dict[str, Any]) -> str:
        name = hit.get("name") or "Документ без названия"
        header_bits = [f"[{index}] {name}"]
        if version := hit.get("version"):
            header_bits.append(f"ред. {version}")
        if numbering := hit.get("numbering"):
            header_bits.append(f"п. {numbering}")
        if fragment_name := hit.get("fragment_name"):
            header_bits.append(fragment_name)
        if node_id := hit.get("id"):
            header_bits.append(f"node_id={node_id}")
        header = ", ".join(header_bits)
        if breadcrumb := hit.get("breadcrumb"):
            header += f" — {breadcrumb}"

        body = (
            hit.get("table_html") or hit.get("context") or hit.get("text") or ""
        ).strip()
        # Never truncate a target or its descendants. Oversized contexts are processed
        # by DvdContextReducer in bounded parallel requests, retaining source labels.
        target = (hit.get("text") or "").strip()
        if target and target not in body and not hit.get("table_html"):
            body = target + "\n" + body
        return f"{header}\n{body}" if body else header
