from __future__ import annotations

import re
from typing import Any

# Record boundaries are generated by the application, not inferred from [N]
# references in the document's bibliography. Escape this character in source text.
SOURCE_SEPARATOR = "\x1e"
TREE_PREFIX = "Дерево источников (полные тексты):\n"


def source_records(context: str) -> dict[str, tuple[str, str]]:
    if context.startswith(TREE_PREFIX):
        return tree_source_records(context[len(TREE_PREFIX) :])
    blocks = (
        context.split(SOURCE_SEPARATOR)
        if SOURCE_SEPARATOR in context
        else re.split(r"(?=^\[\d+\] )", context, flags=re.M)
    )
    records = {}
    for block in filter(None, (b.strip() for b in blocks)):
        header, _, body = block.partition("\n")
        label = re.match(r"^(\[\d+\])(?:\s|$)", header)
        source_id = label[1] if label else "unlabelled"
        if not label:
            header, body = "", block
        if source_id in records:
            body = records[source_id][1] + "\n" + body
        records[source_id] = (header, body)
    return records


def tree_source_records(context: str) -> dict[str, tuple[str, str]]:
    """Restore each shared document/path before independently reducing a source.

    Only application-generated prefixes before [N] modify the scope stack.
    Source text (including apparent headings or [N] references) stays opaque.
    """
    scopes, records = [], {}
    for block in context.split(SOURCE_SEPARATOR):
        lines = block.split("\n")
        for position, line in enumerate(lines):
            label = re.match(r"^\s*(\[\d+\])(?:\s|$)(.*)", line)
            if label:
                header = label[1] + " " + " / ".join(scopes)
                if label[2].strip():
                    header += ", " + label[2].strip()
                records[label[1]] = (header, "\n".join(lines[position + 1 :]).strip())
                break
            if line.strip():
                depth = (len(line) - len(line.lstrip(" "))) // 2
                scopes = scopes[:depth] + [line.strip()]
    return records


class DvdContextBuilder:
    """
    Formats IDU_DVD search hits into a numbered, citable context string for the LLM.

    Each hit becomes a block headed by ``[N] <document>, ред. <version>, п. <numbering> — <breadcrumb>``
    so the answering model can ground its response and cite sources by number and clause.
    """

    def build_context(self, hits: list[dict[str, Any]]) -> str:
        if not hits:
            return ""
        flat = "".join(
            self._format_hit(index, hit).replace(SOURCE_SEPARATOR, "\\u001e")
            + SOURCE_SEPARATOR
            for index, hit in enumerate(self.ordered_hits(hits), start=1)
        )

        if len(hits) < 2:
            return flat
        compact = self._tree_context(hits)
        return compact if len(compact.encode()) < len(flat.encode()) else flat

    def _tree_context(self, hits):
        parts, previous, documents, displays = [], [], {}, {}
        for index, hit in enumerate(self.ordered_hits(hits), 1):
            key = (hit.get("doc_id"), hit.get("name"), hit.get("version"))
            if key not in documents:
                # No document-level labels such as "D1": models cite them instead
                # of the [N] source labels. Only distinct same-named documents
                # get an ordinal, so their scopes are never merged.
                display = "Документ: " + (hit.get("name") or "Документ без названия")
                if hit.get("version"):
                    display += ", ред. " + str(hit["version"])
                displays[display] = displays.get(display, 0) + 1
                if displays[display] > 1:
                    display += (
                        f" (другой документ с тем же названием, {displays[display]})"
                    )
                documents[key] = display
            document = documents[key]
            path = list(hit.get("structure_path") or [])
            number = str(hit.get("numbering") or "")
            own_label = " ".join(filter(None, [number, hit.get("fragment_name")]))
            if path and path[-1] in {number, own_label}:
                path.pop()
            if not hit.get("structure_path"):
                path = [p for p in (hit.get("breadcrumb") or "").split(" / ") if p]
            # A path is taken from source metadata, never guessed from a number.
            scopes = [" ".join(str(p).split()) for p in [document, *path]]
            shared = 0
            while (
                shared < min(len(previous), len(scopes))
                and previous[shared] == scopes[shared]
            ):
                shared += 1
            # Moving to an ancestor must reset the parser's deeper scope stack.
            if shared == len(scopes) and len(previous) > shared:
                shared -= 1
            prefix = "\n".join(
                "  " * depth + scopes[depth] for depth in range(shared, len(scopes))
            )
            header, _, body = self._format_hit(index, hit, compact=True).partition("\n")
            block = (
                (prefix + "\n" if prefix else "")
                + "  " * len(scopes)
                + header
                + "\n"
                + body
            )
            parts.append(
                block.replace(SOURCE_SEPARATOR, "\\u001e") + SOURCE_SEPARATOR + "\n"
            )
            previous = scopes
        return TREE_PREFIX + "".join(parts)

    @staticmethod
    def ordered_hits(hits):
        """Keep document ranking, but quote each source in its reading order.

        Character offsets also cover legacy payloads with missing/zero order.
        The same ordering is used for explanation labels and the full quote.
        """
        groups = {}
        for hit in hits:
            key = (hit.get("doc_id"), hit.get("name"), hit.get("version"))
            groups.setdefault(key, len(groups))
        return sorted(
            hits,
            key=lambda hit: (
                groups[(hit.get("doc_id"), hit.get("name"), hit.get("version"))],
                (
                    hit.get("char_start")
                    if hit.get("char_start") is not None
                    else hit.get("order", 0)
                ),
            ),
        )

    def _format_hit(self, index: int, hit: dict[str, Any], *, compact=False) -> str:
        name = hit.get("name") or "Документ без названия"
        header_bits = [f"[{index}]" if compact else f"[{index}] {name}"]
        if not compact and (version := hit.get("version")):
            header_bits.append(f"ред. {version}")
        if numbering := hit.get("numbering"):
            label = {
                "article": "статья",
                "section": "раздел",
                "chapter": "глава",
                "appendix": "приложение",
                "table": "таблица",
            }.get(hit.get("type"), "п.")
            header_bits.append(f"{label} {numbering}")
        if fragment_name := hit.get("fragment_name"):
            header_bits.append(fragment_name)
        if not compact and hit.get("matched") is not None:
            header_bits.append("полный исходный текст фрагмента")
        header = header_bits[0] + (
            (" " if compact else ", ") + ", ".join(header_bits[1:])
            if len(header_bits) > 1
            else ""
        )
        if not compact and (breadcrumb := hit.get("breadcrumb")):
            header += f" — {breadcrumb}"

        # Neighbour context has no individual source boundaries. It cannot be
        # cited under this hit's address. Descendants arrive as separate hits.
        body = (
            hit.get("table_html") or hit.get("source_text") or hit.get("text") or ""
        ).strip()
        return f"{header}\n{body}" if body else header

    def full_quote(self, hits: list[dict[str, Any]]) -> str:
        """Render every retrieved source in order without model rewriting."""
        blocks = []
        for index, hit in enumerate(self.ordered_hits(hits), 1):
            rendered = self._format_hit(
                index,
                {
                    **hit,
                    "breadcrumb": None,
                    "fragment_name": (
                        hit.get("fragment_name")
                        if hit.get("type")
                        in {"section", "chapter", "article", "appendix", "table"}
                        else None
                    ),
                },
            )
            header, _, body = rendered.partition("\n")
            if not body:
                raise ValueError("Cannot quote a fragment without source text")
            url = hit.get("source_file_url")
            if url and (
                url.startswith(("https://", "http://", "/"))
                and not url.startswith("//")
            ):
                header += (
                    " — [исходный документ]("
                    + url.replace("(", "%28").replace(")", "%29").replace(" ", "%20")
                    + ")"
                )
            blocks.append(
                header + "\n\n" + "\n".join("> " + line for line in body.split("\n"))
            )
        return "Полная цитата:\n\n" + "\n\n".join(blocks)
